# Generated by Django 5.1.3 on 2024-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_remove_tag_notes_note_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='course_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='note_files/'),
        ),
    ]
